version: '3.5'

services:

  app:
    build: ./
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
    ports:
    - '80:5000'
    volumes:
      - ./:/home
    command: bash -c 'python application.py'

  test:
    build: ./
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
    volumes:
      - ./:/home
    command: bash -c 'python -m pytest'